### ISSUE TITLE
Can you tell me where did you implement the learning from the data process?which function?thanks

### ISSUE THREAD

**Issue by RainyCyan** [hesham-saeed/analysis-flood-index#1]

**Comment by hesham-saeed** [comment]
The learning is based on the frequency of the dataset attributes, `getDimsSize2()` is your starting point.

**Comment by RainyCyan** [comment]
Sorry,my previous question may be ambiguous.What I really want to know is the implementation of RMI, such as linear regression.

**Comment by hesham-saeed** [comment]
Current implementation uses Binary Search instead of RMIs. The experiments that utilized RMIs aren't published in this repo. 
Binary Search is thought to be enough for a general purpose usage of the index. 
here is a link to the RMI implementation that was used in the non published experiments: https://github.com/BigDataAnalyticsGroup/analysis-rmi

**Comment by RainyCyan** [comment]
Fine,thanks!
